kind: Task
type: spark
metadata:
  name: show-jira-parquet
spec:
  source:
    - resourceRef: "raw-jira-parquet-dataset"
  options:
    showSample: true
    printSummary: true
    failOnValidationError: false
    debug: true

  operations:
    - type: transform
      transform:
        - select: >
            key,
            summary,
            created,
            updated,
            status,
            labels,
            assignee,
            issue_type,
            project_key
        - filter: "key is not null"

  sink:
    - resourceRef: logger